# See: https://gist.github.com/ky28059/1c9af929a9030105da8cf00006b50484
name: Deploy to vercel on merge
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: sidetrek-docs
          envVariableKeys: WEAVIATE_API_KEY,OPENAI_API_KEY
        env:
          WEAVIATE_API_KEY: ${{ secrets.WEAVIATE_API_KEY }}
          TARGET_WEAVIATE_API_KEY: preview,production
          TYPE_WEAVIATE_API_KEY: encrypted
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TARGET_OPENAI_API_KEY: preview,production
          TYPE_OPENAI_API_KEY: encrypted
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}